[package]
name = "dx-py-modules"
description = "Binary Module Format (DPM) for DX-Py-Runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
memmap2.workspace = true
blake3.workspace = true
dashmap.workspace = true
thiserror.workspace = true
bitflags.workspace = true
dx-py-bytecode = { path = "../dx-py-bytecode" }

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true
tempfile.workspace = true
