[package]
name = "dx-py-package-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "High-performance Python package manager"

[dependencies]
dx-py-core = { path = "../dx-py-core" }
dx-py-compat = { path = "../dx-py-compat" }
thiserror.workspace = true
bytemuck.workspace = true
blake3.workspace = true
memmap2.workspace = true
pubgrub.workspace = true
tempfile = "3.10"
zip = "0.6"
hex = "0.4"
md5 = "0.7"
base64 = "0.22"
dirs = "5.0"
reqwest = { version = "0.11", features = [
    "json",
    "stream",
    "blocking",
    "multipart",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tokio = { version = "1.37", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
    "fs",
] }
futures = "0.3"

[dev-dependencies]
proptest.workspace = true
