[package]
name = "dx-www-guard"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "DOM integrity protection"
keywords = ["wasm", "web", "security", "dx", "dom"]
categories = ["wasm", "web-programming"]

[lib]
path = "src/lib.rs"

[dependencies]
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["MutationObserver"] }
