[package]
name = "dx-compat-html"
version = "0.0.1"
edition = "2021"
description = "HTML Rewriter for DX"
license = "MIT OR Apache-2.0"

[dependencies]
lol_html = "2.0"
thiserror = "2.0"

[dev-dependencies]
proptest = "1.4"
