[package]
name = "dx-bundle-ir"
description = "Binary Intermediate Representation for DX Bundler v2"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dx-bundle-core = { path = "../dx-bundle-core" }
bytemuck.workspace = true
