[package]
name = "dx-bundle-scanner"
description = "SIMD-accelerated pattern matching for DX Bundler v2"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dx-bundle-core = { path = "../dx-bundle-core" }

[features]
default = ["runtime-detect"]
runtime-detect = []
