[package]
name = "dx-py-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
dx-py-core = { path = "../dx-py-core" }
serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
memmap2 = { workspace = true }
shared_memory = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
