[package]
name = "dx-www-interaction"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "User action preservation"
keywords = ["wasm", "web", "interaction", "dx", "input"]
categories = ["wasm", "web-programming"]

[lib]
path = "src/lib.rs"

[dependencies]
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = [
    "HtmlInputElement",
    "Selection",
    "Window",
] }
